GET http://localhost:6800

###

GET http://localhost:6800/users

###

GET http://localhost:6800/users/1

###

GET http://localhost:6800/users/email/test4@gmail.com/test4

###

POST http://localhost:6800/users
Content-Type: application/json

{
    "username": "Test 1",
    "email": "test1@gmail.com",
    "address": "Sukapura"
}

###

POST http://localhost:6800/users/login
Content-Type: application/json

{
    "email": "test4@gmail.com",
    "password": "test4"
}